version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env.docker
    volumes:
        - db-data:/var/lib/mysql
        - ./db/conf:/etc/mysql/conf.d
        - ./db/initdb:/docker-entrypoint-initdb.d # test用dbが必要な場合

  migration:
    dns: 8.8.8.8
    build:
      context: .
      dockerfile: Dockerfile-migration
    depends_on:
      - db

  app:
    dns: 8.8.8.8
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - migration
    environment:
    - CHOKIDAR_USEPOLLING=true

volumes:
  db-data: