version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
        - 3306:3306
    volumes:
        - db-data:/var/lib/mysql
        - ./db/conf:/etc/mysql/conf.d
        - ./db/initdb:/docker-entrypoint-initdb.d # test用dbが必要な場合
volumes:
  db-data: