version: '3'

services:
  app:
    dns: 8.8.8.8
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - ./app:/app/app
    restart: always
    ports:
      - "8000:8000"
    environment:
    command: uvicorn app.main:app --host 0.0.0.0 
