FROM python:3.8

COPY ./app /app/app
COPY ./.env.docker /.env
COPY ./requirements.txt /requirements.txt

RUN echo 'nameserver 8.8.8.8' > /etc/resolv.conf  && \
    python3 -m pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8000

WORKDIR /app

CMD ["uvicorn", "app.main:app","--host", "0.0.0.0","--reload"]