FROM python:3.8

COPY ./app /app/app
COPY ./.env.docker /.env
COPY ./requirements.txt /requirements.txt
COPY ./wait-for-it.sh /app

RUN chmod 555 /app/wait-for-it.sh && \
    echo 'nameserver 8.8.8.8' > /etc/resolv.conf  && \
    python3 -m pip install --upgrade pip -q && \
    pip install -r requirements.txt -q

EXPOSE 8000

WORKDIR /app

