version: "3"

services:
  db:
    image: mysql:8
    container_name: quaint-api-mysql
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - quaint-api-db:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
      - ./db/initdb:/docker-entrypoint-initdb.d # test用dbが必要な場合

  app:
    image: python:3.8
    depends_on:
      - db
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "8010:8000"
    command: /bin/bash /workspace/docker_startup.sh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: "db"
    ports:
      - "8090:80"
volumes:
  quaint-api-db-dev:
