FROM python:3.8

COPY ./app /app
COPY ./.env.docker /.env
COPY ./requirements.txt /requirements.txt

COPY ./migration /migration
COPY ./wait-for-it.sh /migration

RUN chmod 555 /migration/wait-for-it.sh && \
    echo 'nameserver 8.8.8.8' > /etc/resolv.conf && \
    python3 -m pip install --upgrade pip -q && \
    pip install -r requirements.txt -q

WORKDIR /migration
