FROM python:3.8

COPY ./app /app/app
COPY ./.env /
COPY ./requirements.txt /requirements.txt

RUN pip install -r requirements.txt

EXPOSE 8000

WORKDIR /app

CMD ["uvicorn", "app.main:app","--host", "0.0.0.0","--reload"]