version: "3"

services:
  app:
    image: python:3.8
    depends_on:
      - db
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
    command: /bin/bash /workspace/docker_startup.sh

  redis:
    image: "redis:latest"
    volumes:
      - "./redis.conf:/etc/redis.conf"
