version: "3"

services:
  app:
    image: python:3.8
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
    command: /bin/bash /workspace/docker_startup.sh

  redis:
    image: "redis:latest"
    volumes:
      - "./redis.conf:/etc/redis.conf"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment: 
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
