version: "3"

services:
  db:
    image: mysql:8
    container_name: quaint-api-mysql
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "3306:3306"
    volumes:
      - quaint-api-db:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
      - ./db/initdb:/docker-entrypoint-initdb.d # test用dbが必要な場合
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: "db"
    ports:
      - "8080:80"
volumes:
  quaint-api-db:
