"""change table name

Revision ID: 04e093449225
Revises: e6fb7a3a7165
Create Date: 2023-03-17 20:32:52.609801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04e093449225'
down_revision = 'e6fb7a3a7165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sell_starts', sa.DateTime(), nullable=False),
    sa.Column('sell_ends', sa.DateTime(), nullable=False),
    sa.Column('ticket_stock', sa.Integer(), nullable=False),
    sa.Column('lottery', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_id'), 'distribution', ['id'], unique=True)
    op.drop_index('ix_sellmethods_id', table_name='sellmethods')
    op.drop_table('sellmethods')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellmethods',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sell_ends', mysql.DATETIME(), nullable=False),
    sa.Column('ticket_stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lottery', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sell_starts', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='sellmethods_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sellmethods_id', 'sellmethods', ['id'], unique=False)
    op.drop_index(op.f('ix_distribution_id'), table_name='distribution')
    op.drop_table('distribution')
    # ### end Alembic commands ###
