"""add image_url to Group

Revision ID: 07e5f3151e2d
Revises: f93b4ff35ac4
Create Date: 2022-09-03 14:02:18.219345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e5f3151e2d'
down_revision = 'f93b4ff35ac4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('thumbnail_image_url', sa.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('cover_image_url', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'cover_image_url')
    op.drop_column('groups', 'thumbnail_image_url')
    # ### end Alembic commands ###
