"""specify timezone

Revision ID: 0e7339e35acd
Revises: b6fd2810c838
Create Date: 2023-03-19 17:17:41.937543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7339e35acd'
down_revision = 'b6fd2810c838'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
