"""relationship GroupTag bug fix4

Revision ID: 0f2fd4c9cd2d
Revises: 186a6ead67d2
Create Date: 2022-07-15 23:48:20.633993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2fd4c9cd2d'
down_revision = '186a6ead67d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
