"""delete relationship votes with users

Revision ID: 10896a7cb4a1
Revises: 2a0268518ee8
Create Date: 2022-07-12 01:00:22.816096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10896a7cb4a1'
down_revision = '2a0268518ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
