"""empty message

Revision ID: 130d1f0a7be2
Revises: 2872d47bda6f
Create Date: 2023-03-08 18:43:01.841657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130d1f0a7be2'
down_revision = '2872d47bda6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sell_at', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('sell_ends', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'sell_ends')
    op.drop_column('events', 'sell_at')
    # ### end Alembic commands ###
