"""relationship GroupTag bug fix3

Revision ID: 186a6ead67d2
Revises: a02d470fafec
Create Date: 2022-07-15 23:45:50.436547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186a6ead67d2'
down_revision = 'a02d470fafec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
