"""delete relationship group event

Revision ID: 2171f8479fb0
Revises: cbcf94945332
Create Date: 2022-07-12 00:37:03.492487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2171f8479fb0'
down_revision = 'cbcf94945332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
