"""empty message

Revision ID: 2872d47bda6f
Revises: ada04d693a85
Create Date: 2023-03-08 18:34:05.434230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2872d47bda6f'
down_revision = 'ada04d693a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('target', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'target')
    # ### end Alembic commands ###
