"""delete relationship votes

Revision ID: 2a0268518ee8
Revises: a9b7677ceb1f
Create Date: 2022-07-12 00:59:41.294120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0268518ee8'
down_revision = 'a9b7677ceb1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
