"""change group

Revision ID: 3f22385d2cfe
Revises: 294c5365ed4f
Create Date: 2023-03-05 17:07:07.151757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f22385d2cfe'
down_revision = '294c5365ed4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('public_page_content_url', sa.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('public_thumbnail_image_url', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('groups', 'cover_image_url')
    op.drop_column('groups', 'thumbnail_image_url')
    op.drop_column('groups', 'page_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('page_content', mysql.TEXT(), nullable=True))
    op.add_column('groups', sa.Column('thumbnail_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('cover_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('groups', 'public_thumbnail_image_url')
    op.drop_column('groups', 'public_page_content_url')
    # ### end Alembic commands ###
