"""add name to grouplink

Revision ID: 48a69541f5a1
Revises: ed2dadbab177
Create Date: 2023-09-18 13:32:04.599744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a69541f5a1'
down_revision = 'ed2dadbab177'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grouplinks', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grouplinks', 'name')
    # ### end Alembic commands ###
