"""add group list to tag back_populates

Revision ID: 4a13bea2e0ae
Revises: 684b3d00fbeb
Create Date: 2022-07-24 20:01:00.712712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a13bea2e0ae'
down_revision = '684b3d00fbeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
