"""relationship GroupTag bug fix1

Revision ID: 4bcee8c5b097
Revises: cacb096536cc
Create Date: 2022-07-15 02:11:41.602806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcee8c5b097'
down_revision = 'cacb096536cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
