"""add group list to tag back_populate rollback

Revision ID: 4c50fae371b4
Revises: 4a13bea2e0ae
Create Date: 2022-07-24 20:14:27.025226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c50fae371b4'
down_revision = '4a13bea2e0ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
