"""add group_id to ticket

Revision ID: 5272fa2f0f79
Revises: c9616a3bbdf6
Create Date: 2022-08-21 21:56:41.027201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5272fa2f0f79'
down_revision = 'c9616a3bbdf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('group_id', sa.VARCHAR(length=255), nullable=True))
    op.create_foreign_key(None, 'tickets', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'group_id')
    # ### end Alembic commands ###
