"""datetimeをstrで保存

Revision ID: 54170e2cf7d9
Revises: ea293e7fbb5d
Create Date: 2023-03-19 20:55:57.427555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54170e2cf7d9'
down_revision = 'ea293e7fbb5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
