"""readauthority

Revision ID: 5a064c2417c4
Revises: 7b661744b4fa
Create Date: 2023-07-26 18:51:36.952594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a064c2417c4'
down_revision = '7b661744b4fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readauthority',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('idp', sa.VARCHAR(length=255), nullable=False),
    sa.Column('b2c_visited', sa.Boolean(), nullable=True),
    sa.Column('ad_group', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idp', 'b2c_visited', 'ad_group', name='unique_idpx_b2c_visited_ad_group')
    )
    op.create_index(op.f('ix_readauthority_id'), 'readauthority', ['id'], unique=True)
    op.create_table('eventreadauthority',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('readauthority_id', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['readauthority_id'], ['readauthority.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'readauthority_id', name='unique_idx_eventid_readauthorityid')
    )
    op.create_index(op.f('ix_eventreadauthority_id'), 'eventreadauthority', ['id'], unique=True)
    op.drop_column('events', 'target')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('target', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_eventreadauthority_id'), table_name='eventreadauthority')
    op.drop_table('eventreadauthority')
    op.drop_index(op.f('ix_readauthority_id'), table_name='readauthority')
    op.drop_table('readauthority')
    # ### end Alembic commands ###
