"""何階かと場所の情報の追加

Revision ID: 5dcb60747449
Revises: 48a69541f5a1
Create Date: 2024-03-05 12:37:57.507724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcb60747449'
down_revision = '48a69541f5a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('floor', sa.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('place', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'place')
    op.drop_column('groups', 'floor')
    # ### end Alembic commands ###
