"""add group list to tag

Revision ID: 684b3d00fbeb
Revises: 75c62e6a55b3
Create Date: 2022-07-24 19:55:52.285510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684b3d00fbeb'
down_revision = '75c62e6a55b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
