"""grouptag primary_key

Revision ID: 69b0d4a548fc
Revises: 07e5f3151e2d
Create Date: 2022-09-03 14:29:40.313491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69b0d4a548fc'
down_revision = '07e5f3151e2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='grouptag')
    op.drop_column('grouptag', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grouptag', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('id', 'grouptag', ['id'], unique=False)
    # ### end Alembic commands ###
