"""delete relationship

Revision ID: 6a01bce897e6
Revises: 4c50fae371b4
Create Date: 2022-08-07 20:57:39.683365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a01bce897e6'
down_revision = '4c50fae371b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
