"""delete relationship group users votes

Revision ID: 6ff1d3c098ad
Revises: 2171f8479fb0
Create Date: 2022-07-12 00:46:09.382523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff1d3c098ad'
down_revision = '2171f8479fb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
