"""add urls to Group

Revision ID: 75c62e6a55b3
Revises: 942282ee6b4d
Create Date: 2022-07-22 17:39:19.819604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c62e6a55b3'
down_revision = '942282ee6b4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('twitter_url', sa.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('instagram_url', sa.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('stream_url', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'stream_url')
    op.drop_column('groups', 'instagram_url')
    op.drop_column('groups', 'twitter_url')
    # ### end Alembic commands ###
