"""add management note to groupowner

Revision ID: 7b661744b4fa
Revises: f89f4e639934
Create Date: 2023-07-16 07:19:16.340050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b661744b4fa'
down_revision = 'f89f4e639934'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupowners', sa.Column('note', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupowners', 'note')
    # ### end Alembic commands ###
