"""add is_student Column to User table

Revision ID: 8180339039a3
Revises: 7abcad91fcd3
Create Date: 2022-07-02 17:27:22.009446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8180339039a3'
down_revision = '7abcad91fcd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_student')
    # ### end Alembic commands ###
