"""empty message

Revision ID: 87e4609f1052
Revises: 130d1f0a7be2
Create Date: 2023-03-08 18:43:34.737557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e4609f1052'
down_revision = '130d1f0a7be2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lottery', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'lottery')
    # ### end Alembic commands ###
