"""relationship test

Revision ID: 942282ee6b4d
Revises: 9982948e73fb
Create Date: 2022-07-16 15:36:18.790641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942282ee6b4d'
down_revision = '9982948e73fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
