"""6

Revision ID: 9982948e73fb
Revises: e00f828e767e
Create Date: 2022-07-16 00:02:07.065242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9982948e73fb'
down_revision = 'e00f828e767e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
