"""relationship GroupTag bug fix2

Revision ID: a02d470fafec
Revises: 4bcee8c5b097
Create Date: 2022-07-15 02:16:30.569406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02d470fafec'
down_revision = '4bcee8c5b097'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
