"""relationship

Revision ID: a9b7677ceb1f
Revises: 6ff1d3c098ad
Create Date: 2022-07-12 00:57:43.450422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b7677ceb1f'
down_revision = '6ff1d3c098ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
