"""add groupowner

Revision ID: ada04d693a85
Revises: f2f58a82c6c1
Create Date: 2023-03-05 19:07:43.535442

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ada04d693a85'
down_revision = 'f2f58a82c6c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupowners',
    sa.Column('group_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('sellmethods',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sell_at', sa.DateTime(), nullable=False),
    sa.Column('sell_ends', sa.DateTime(), nullable=False),
    sa.Column('ticket_stock', sa.Integer(), nullable=False),
    sa.Column('lottery', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellmethods_id'), 'sellmethods', ['id'], unique=True)
    op.drop_constraint('events_ibfk_2', 'events', type_='foreignkey')
    op.drop_index('unique_timetablex_groupid', table_name='events')
    op.drop_index('ix_timetable_id', table_name='timetable')
    op.drop_table('timetable')
    op.add_column('events', sa.Column('eventname', sa.VARCHAR(length=255), nullable=True))
    op.add_column('events', sa.Column('starts_at', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('ends_at', sa.DateTime(), nullable=False))
    
    op.drop_column('events', 'lottery')
    op.drop_column('events', 'timetable_id')
    op.drop_column('groups', 'private_thumbnail_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('private_thumbnail_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('events', sa.Column('timetable_id', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('events', sa.Column('lottery', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_foreign_key('events_ibfk_2', 'events', 'timetable', ['timetable_id'], ['id'])
    op.create_index('unique_timetablex_groupid', 'events', ['timetable_id', 'group_id'], unique=False)
    op.drop_column('events', 'ends_at')
    op.drop_column('events', 'starts_at')
    op.drop_column('events', 'eventname')
    op.create_table('timetable',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('timetablename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sell_at', mysql.DATETIME(), nullable=False),
    sa.Column('sell_ends', mysql.DATETIME(), nullable=False),
    sa.Column('starts_at', mysql.DATETIME(), nullable=False),
    sa.Column('ends_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_timetable_id', 'timetable', ['id'], unique=False)
    op.drop_index(op.f('ix_sellmethods_id'), table_name='sellmethods')
    op.drop_table('sellmethods')
    op.drop_table('groupowners')
    # ### end Alembic commands ###
