"""specify timezone

Revision ID: b6fd2810c838
Revises: ecb1bb9c7ccb
Create Date: 2023-03-19 16:25:30.140616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fd2810c838'
down_revision = 'ecb1bb9c7ccb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
