"""uniqueconstraint to Authority

Revision ID: b7e4fdce33b3
Revises: a1cee85ccc50
Create Date: 2022-09-03 14:53:00.011238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7e4fdce33b3'
down_revision = 'a1cee85ccc50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authority', 'role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('id', table_name='authority')
    op.create_unique_constraint('unique_idx_groupid_tagid', 'authority', ['user_id', 'group_id', 'role'])
    op.drop_column('authority', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authority', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('unique_idx_groupid_tagid', 'authority', type_='unique')
    op.create_index('id', 'authority', ['id'], unique=False)
    op.alter_column('authority', 'role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
