"""use ULID

Revision ID: bcca8fd41885
Revises: 6a01bce897e6
Create Date: 2022-08-10 01:55:45.425833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcca8fd41885'
down_revision = '6a01bce897e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authority_id', table_name='authority')
    op.drop_column('authority', 'id')
    op.drop_index('ix_events_id', table_name='events')
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=True)
    op.drop_index('ix_groups_id', table_name='groups')
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=True)
    op.drop_index('ix_grouptag_id', table_name='grouptag')
    op.drop_column('grouptag', 'id')
    op.drop_index('ix_tags_id', table_name='tags')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=True)
    op.drop_index('ix_tickets_id', table_name='tickets')
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=True)
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_index('ix_votes_id', table_name='votes')
    op.drop_column('votes', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_votes_id', 'votes', ['id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.create_index('ix_tickets_id', 'tickets', ['id'], unique=False)
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    op.add_column('grouptag', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_grouptag_id', 'grouptag', ['id'], unique=False)
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.create_index('ix_groups_id', 'groups', ['id'], unique=False)
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.add_column('authority', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_authority_id', 'authority', ['id'], unique=False)
    # ### end Alembic commands ###
