"""use timetable

Revision ID: c9616a3bbdf6
Revises: 72f93fdecdde
Create Date: 2022-08-19 23:32:21.400838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9616a3bbdf6'
down_revision = '72f93fdecdde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timetablename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sell_at', sa.DateTime(), nullable=False),
    sa.Column('sell_ends', sa.DateTime(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_id'), 'timetable', ['id'], unique=True)
    op.add_column('events', sa.Column('timetable_id', sa.VARCHAR(length=255), nullable=False))
    op.add_column('events', sa.Column('lottery', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'events', 'timetable', ['timetable_id'], ['id'])
    op.drop_column('events', 'sell_ends')
    op.drop_column('events', 'ends_at')
    op.drop_column('events', 'description')
    op.drop_column('events', 'starts_at')
    op.drop_column('events', 'title')
    op.drop_column('events', 'sell_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sell_at', mysql.DATETIME(), nullable=False))
    op.add_column('events', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('events', sa.Column('starts_at', mysql.DATETIME(), nullable=False))
    op.add_column('events', sa.Column('description', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('events', sa.Column('ends_at', mysql.DATETIME(), nullable=False))
    op.add_column('events', sa.Column('sell_ends', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'lottery')
    op.drop_column('events', 'timetable_id')
    op.drop_index(op.f('ix_timetable_id'), table_name='timetable')
    op.drop_table('timetable')
    # ### end Alembic commands ###
