"""relationship GroupTag

Revision ID: cacb096536cc
Revises: 10896a7cb4a1
Create Date: 2022-07-15 02:11:02.080151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacb096536cc'
down_revision = '10896a7cb4a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
