"""canceled change

Revision ID: cbcf94945332
Revises: e88fdb283c1e
Create Date: 2022-07-11 00:21:33.576295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcf94945332'
down_revision = 'e88fdb283c1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
