"""votesystem

Revision ID: d48d3a3875e4
Revises: 278ab09027c9
Create Date: 2023-09-14 18:27:05.659665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd48d3a3875e4'
down_revision = '278ab09027c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('group_id_21', sa.VARCHAR(length=255), nullable=True))
    op.add_column('votes', sa.Column('group_id_11', sa.VARCHAR(length=255), nullable=True))
    op.create_unique_constraint(None, 'votes', ['user_id'])
    op.drop_constraint('votes_ibfk_1', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'groups', ['group_id_21'], ['id'])
    op.create_foreign_key(None, 'votes', 'groups', ['group_id_11'], ['id'])
    op.drop_column('votes', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('group_id', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_ibfk_1', 'votes', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'votes', type_='unique')
    op.drop_column('votes', 'group_id_11')
    op.drop_column('votes', 'group_id_21')
    # ### end Alembic commands ###
