"""relationship GroupTag bug fix5

Revision ID: e00f828e767e
Revises: 0f2fd4c9cd2d
Create Date: 2022-07-15 23:57:29.755127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00f828e767e'
down_revision = '0f2fd4c9cd2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
