"""ticket.is_used->ticket.status

Revision ID: e6f6f1366a60
Revises: 7b661744b4fa
Create Date: 2023-08-07 15:55:09.780056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6f6f1366a60'
down_revision = '7b661744b4fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text('"active"'), nullable=False))
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.drop_column('tickets', 'is_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
