"""add distribution

Revision ID: e6fb7a3a7165
Revises: 87e4609f1052
Create Date: 2023-03-17 18:45:10.629495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6fb7a3a7165'
down_revision = '87e4609f1052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'sell_ends')
    op.drop_column('events', 'lottery')
    op.drop_column('events', 'sell_at')
    op.add_column('sellmethods', sa.Column('sell_starts', sa.DateTime(), nullable=False))
    op.drop_column('sellmethods', 'sell_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellmethods', sa.Column('sell_at', mysql.DATETIME(), nullable=False))
    op.drop_column('sellmethods', 'sell_starts')
    op.add_column('events', sa.Column('sell_at', mysql.DATETIME(), nullable=False))
    op.add_column('events', sa.Column('lottery', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('sell_ends', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
