"""relationship test

Revision ID: e88fdb283c1e
Revises: 89ff494f1996
Create Date: 2022-07-11 00:16:19.701133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88fdb283c1e'
down_revision = '89ff494f1996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
