"""TIMESTAMP

Revision ID: ea293e7fbb5d
Revises: 0e7339e35acd
Create Date: 2023-03-19 17:30:05.687235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea293e7fbb5d'
down_revision = '0e7339e35acd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
