"""grouplink

Revision ID: ed2dadbab177
Revises: d48d3a3875e4
Create Date: 2023-09-18 12:19:02.515156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2dadbab177'
down_revision = 'd48d3a3875e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grouplinks',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('linktext', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id', 'group_id')
    )
    op.create_index(op.f('ix_grouplinks_id'), 'grouplinks', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grouplinks_id'), table_name='grouplinks')
    op.drop_table('grouplinks')
    # ### end Alembic commands ###
