"""change group add private

Revision ID: f2f58a82c6c1
Revises: 3f22385d2cfe
Create Date: 2023-03-05 17:13:47.591292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f58a82c6c1'
down_revision = '3f22385d2cfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('private_thumbnail_image_url', sa.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('private_page_content_url', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'private_page_content_url')
    op.drop_column('groups', 'private_thumbnail_image_url')
    # ### end Alembic commands ###
