"""create tables first

Revision ID: f40b206848e3
Revises: 
Create Date: 2022-06-19 23:51:38.678086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40b206848e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.NullType(), nullable=True),
    sa.Column('name', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
