"""2023

Revision ID: f89f4e639934
Revises: ca7a48e36a7d
Create Date: 2023-03-23 01:11:00.754867

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f89f4e639934'
down_revision = 'ca7a48e36a7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupowners',
    sa.Column('group_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.drop_constraint('events_ibfk_2', 'events', type_='foreignkey')
    op.drop_constraint('tickets_ibfk_3', 'tickets', type_='foreignkey')
    op.drop_constraint('votes_ibfk_2', 'votes', type_='foreignkey')
    op.drop_index('ix_timetable_id', table_name='timetable')
    op.drop_index('unique_timetablex_groupid', table_name='events')
    op.drop_index('user_id', table_name='admin')
    op.drop_index('user_id', table_name='entry')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('unique_idx_groupid_tagid', table_name='authority')
    op.drop_index('ix_log_id', table_name='log')
    op.drop_index('unique_useridx_groupid', table_name='like')
    op.drop_table('timetable')
    op.drop_table('balloon')
    op.drop_table('like')
    op.drop_table('comment')
    op.drop_table('log')
    op.drop_table('authority')
    op.drop_table('admin')
    op.drop_table('entry')
    op.drop_table('users')
    op.add_column('events', sa.Column('eventname', sa.VARCHAR(length=255), nullable=True))
    op.add_column('events', sa.Column('starts_at', sa.VARCHAR(length=255), nullable=False))
    op.add_column('events', sa.Column('ends_at', sa.VARCHAR(length=255), nullable=False))
    op.add_column('events', sa.Column('sell_starts', sa.VARCHAR(length=255), nullable=False))
    op.add_column('events', sa.Column('sell_ends', sa.VARCHAR(length=255), nullable=False))
    op.add_column('events', sa.Column('target', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('events', 'timetable_id')
    op.add_column('groups', sa.Column('public_thumbnail_image_url', sa.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('public_page_content_url', sa.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('private_page_content_url', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('groups', 'thumbnail_image_url')
    op.drop_column('groups', 'cover_image_url')
    op.drop_column('groups', 'page_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('votes_ibfk_2', 'votes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('tickets_ibfk_3', 'tickets', 'users', ['owner_id'], ['id'])
    op.add_column('groups', sa.Column('page_content', mysql.TEXT(), nullable=True))
    op.add_column('groups', sa.Column('cover_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('thumbnail_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('groups', 'private_page_content_url')
    op.drop_column('groups', 'public_page_content_url')
    op.drop_column('groups', 'public_thumbnail_image_url')
    op.add_column('events', sa.Column('timetable_id', mysql.VARCHAR(length=255), nullable=False))
    op.create_foreign_key('events_ibfk_2', 'events', 'timetable', ['timetable_id'], ['id'])
    op.create_index('unique_timetablex_groupid', 'events', ['timetable_id', 'group_id'], unique=False)
    op.drop_column('events', 'target')
    op.drop_column('events', 'sell_ends')
    op.drop_column('events', 'sell_starts')
    op.drop_column('events', 'ends_at')
    op.drop_column('events', 'starts_at')
    op.drop_column('events', 'eventname')
    op.create_table('entry',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='entry_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'entry', ['user_id'], unique=False)
    op.create_table('admin',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='admin_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'admin', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_student', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_family', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('password_expired', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('authority',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='authority_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='authority_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', 'role'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_idx_groupid_tagid', 'authority', ['user_id', 'group_id', 'role'], unique=False)
    op.create_table('log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('object', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('operation', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('result', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('detail', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_log_id', 'log', ['id'], unique=False)
    op.create_table('comment',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('visibility', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='comment_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comment_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('like',
    sa.Column('group_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='like_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='like_ibfk_2'),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_useridx_groupid', 'like', ['group_id', 'user_id'], unique=False)
    op.create_table('balloon',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('endpoint', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='balloon_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'endpoint'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('timetable',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('timetablename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sell_at', mysql.DATETIME(), nullable=False),
    sa.Column('sell_ends', mysql.DATETIME(), nullable=False),
    sa.Column('starts_at', mysql.DATETIME(), nullable=False),
    sa.Column('ends_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_timetable_id', 'timetable', ['id'], unique=False)
    op.drop_table('groupowners')
    # ### end Alembic commands ###
